# Generated by Django 5.0.1 on 2026-03-29 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(max_length=40)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("MAIN_INLET", "Main Inlet"),
                            ("TANK", "Tank"),
                            ("UNIT_METER", "Unit Meter"),
                            ("PIPELINE", "Pipeline"),
                            ("QUALITY_POINT", "Quality Point"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="orgs.hostel",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="orgs.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["hostel__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("serial_number", models.CharField(max_length=80, unique=True)),
                ("firmware_version", models.CharField(blank=True, max_length=40)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="iot.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["asset__hostel__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(max_length=40)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("FLOW", "Flow"),
                            ("LEVEL", "Level"),
                            ("PRESSURE", "Pressure"),
                            ("PH", "pH"),
                            ("TURBIDITY", "Turbidity"),
                            ("TDS", "TDS"),
                            ("TEMPERATURE", "Temperature"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unit_symbol", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="iot.device",
                    ),
                ),
            ],
            options={
                "ordering": ["device__asset__hostel__name", "kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("value", models.DecimalField(decimal_places=3, max_digits=12)),
                ("ingest_source", models.CharField(default="simulated", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="iot.sensor",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["hostel", "asset_type"], name="iot_asset_hostel__cb4daa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["unit"], name="iot_asset_unit_id_7b2261_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["is_active"], name="iot_asset_is_acti_384502_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("hostel", "code"), name="unique_asset_code_per_hostel"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["asset", "is_active"], name="iot_device_asset_i_d8d1da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["last_seen_at"], name="iot_device_last_se_cf65b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensor",
            index=models.Index(
                fields=["kind", "status"], name="iot_sensor_kind_6da36d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensor",
            index=models.Index(
                fields=["is_active"], name="iot_sensor_is_acti_09444c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sensor",
            constraint=models.UniqueConstraint(
                fields=("device", "code"), name="unique_sensor_code_per_device"
            ),
        ),
        migrations.AddIndex(
            model_name="reading",
            index=models.Index(
                fields=["sensor", "timestamp"], name="iot_reading_sensor__cb6f52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reading",
            index=models.Index(
                fields=["timestamp"], name="iot_reading_timesta_f9a069_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reading",
            constraint=models.UniqueConstraint(
                fields=("sensor", "timestamp"), name="unique_sensor_timestamp_reading"
            ),
        ),
    ]
