# Generated by Django 5.0.1 on 2026-03-29 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(max_length=40, unique=True)),
                (
                    "campus_name",
                    models.CharField(default="Main Campus", max_length=120),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="orgs_hostel_is_acti_3c4201_idx"
                    ),
                    models.Index(
                        fields=["campus_name"], name="orgs_hostel_campus__6b41d1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(max_length=40)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[("FLOOR", "Floor"), ("CLUSTER", "Cluster")],
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="orgs.hostel",
                    ),
                ),
            ],
            options={
                "ordering": ["hostel__name", "unit_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["hostel", "unit_type"],
                        name="orgs_unit_hostel__722d93_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="orgs_unit_is_acti_732fe3_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("hostel", "code"), name="unique_unit_code_per_hostel"
            ),
        ),
    ]
