# Generated by Django 5.0.1 on 2026-03-29 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iot", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("CAMPUS", "Campus"),
                            ("HOSTEL", "Hostel"),
                            ("UNIT", "Unit"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("BASELINE", "Baseline"), ("AI", "AI")],
                        default="BASELINE",
                        max_length=10,
                    ),
                ),
                ("horizon_hours", models.PositiveIntegerField(default=24)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "hostel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forecast_runs",
                        to="orgs.hostel",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forecast_runs",
                        to="orgs.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ForecastPoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "predicted_value",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "lower_bound",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "upper_bound",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "forecast_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="ops.forecastrun",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ThresholdRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("NIGHT_CONTINUOUS_FLOW", "Night Continuous Flow"),
                            ("BLOCKAGE_PATTERN", "Blockage Pattern"),
                            ("TANK_LOW", "Tank Low"),
                            ("TANK_OVERFLOW_RISK", "Tank Overflow Risk"),
                            ("QUALITY_PH", "pH Exceedance"),
                            ("QUALITY_TURBIDITY", "Turbidity Exceedance"),
                            ("QUALITY_TDS", "TDS Exceedance"),
                            ("SENSOR_OFFLINE_MINUTES", "Sensor Offline Minutes"),
                            (
                                "CAMPUS_INLET_DIFF_PERCENT",
                                "Campus Inlet Difference Percent",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("warning_value", models.FloatField()),
                ("critical_value", models.FloatField()),
                ("unit_symbol", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threshold_rules",
                        to="orgs.hostel",
                    ),
                ),
            ],
            options={
                "ordering": ["rule_type", "hostel__name"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARN", "Warn"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("LEAK_SUSPECTED", "Leak Suspected"),
                            ("BLOCKAGE_SUSPECTED", "Blockage Suspected"),
                            ("TANK_LOW", "Tank Low"),
                            ("OVERFLOW_RISK", "Overflow Risk"),
                            ("QUALITY_EXCEEDANCE", "Quality Exceedance"),
                            ("SENSOR_OFFLINE", "Sensor Offline"),
                            ("ABNORMAL_USAGE", "Abnormal Usage"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.CharField(max_length=300)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="iot.asset",
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="orgs.hostel",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="iot.sensor",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="orgs.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["severity", "alert_type"],
                        name="ops_alert_severit_f52f3f_idx",
                    ),
                    models.Index(
                        fields=["hostel", "unit"], name="ops_alert_hostel__3d1e5d_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="ops_alert_started_7768fd_idx"
                    ),
                    models.Index(
                        fields=["acknowledged_at"], name="ops_alert_acknowl_eede4b_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="forecastrun",
            index=models.Index(
                fields=["scope_type", "generated_at"],
                name="ops_forecas_scope_t_7ded5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forecastrun",
            index=models.Index(
                fields=["hostel", "unit"], name="ops_forecas_hostel__4a4929_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forecastpoint",
            index=models.Index(
                fields=["forecast_run", "timestamp"],
                name="ops_forecas_forecas_8c9d43_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastpoint",
            constraint=models.UniqueConstraint(
                fields=("forecast_run", "timestamp"),
                name="unique_forecast_point_timestamp",
            ),
        ),
        migrations.AddIndex(
            model_name="thresholdrule",
            index=models.Index(
                fields=["hostel", "rule_type"], name="ops_thresho_hostel__f42a83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thresholdrule",
            index=models.Index(
                fields=["is_active"], name="ops_thresho_is_acti_aa1f87_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="thresholdrule",
            constraint=models.UniqueConstraint(
                fields=("hostel", "rule_type"), name="unique_threshold_per_scope"
            ),
        ),
    ]
